Merge branch 'current' into next
mattyhall/rs-tiled pull request #246
Opened 2023-02-12 21:34 UTC by bjorn

Quite a few changes were made on `current` so I think it's worth merging them into `next`. I had to resolve some conflicts in the CI workflow and `objects.rs`.

2023-02-12 21:39 UTC, aleokdev approved these changes

2023-02-12 21:41 UTC, aleokdev requested changes
Hold up, is the base branch `next` as well or is my phone acting up?

2023-02-13 08:34 UTC, bjorn commented
> Hold up, is the base branch `next` as well or is my phone acting up?

Should be, it's looking fine to me:

![image](https://user-images.githubusercontent.com/531764/218408984-e3e81aaa-965d-49aa-864e-47cf328d3d8f.png)

2023-02-13 09:33 UTC, aleokdev approved these changes

2023-02-13 09:37 UTC, merged